### ISSUE TITLE
Size of corpus?

### ISSUE THREAD

**Issue by AndBM** [paalberti/tesseract-dan-fraktur#5]
Do you know the approximate size of the corpus you have trained on?

**Comment by paalberti** [comment]
The images are in the repository.
If you meant the wordlists, the Danish one is based on texts of about 800,000 words in total and the German one is based on texts of about 400,000 words in total. The Swedish is larger but as it isn't mine, I don't have the size of the original texts. There is no real training done on wordlists, though.
